### ISSUE TITLE
No way to quit

### ISSUE THREAD

**Issue by CraigEMP** [chairmanmow/synchro_trail#2]
There's no way for a user to exit the game once entered.  He/she must either die or complete the game before being allowed to quit back to the BBS.  This often results in users simply hanging-up on the BBS after starting.

A simple menu at the beginning like 1-Play, 2-Instructions, 3-Quit, or even a courtesy prompt  asking, "are you ready?" would make it both caller and BBS friendly.

**Comment by chairmanmow** [comment]
I don't currently have a Synchronet BBS set up to test on, but I can try making this change by looking at the code if you don't mind testing it?

**Comment by CraigEMP** [comment]
Yes, gladly.

**Comment by chairmanmow** [comment]
Sounds good, should be able to get to it in the next few days if not sooner - I'll ping you when there's some new code up to run.

**Comment by chairmanmow** [comment]
@CraigEMP Think I was able to make the change, wasn't too hard, hope it works!  Let me know if you run into any issues or if  it's good I'll merge this into my master branch.  https://github.com/chairmanmow/synchro_trail/pull/3/files
